language: java
jdk: openjdk8
services:
  - xvfb
addons:
  chrome: stable
  apt:
    packages:
      - python3-pip
      - python3-setuptools
      - python3-wheel

before_script:
  # Use a newer version of Python
  - pyenv versions
  - pyenv global 3.6
  # Setup biotestmine to test against
  - pip3 install intermine-boot
  - intermine_boot start local --build-im --im-branch bluegenes
  # Install lein - required to build the project
  - wget https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein -O /tmp/lein
  - chmod +x /tmp/lein
  - export PATH=$PATH:/tmp/lein
  # make several attempts at downloading dependencies
  - travis_retry lein deps
  # check code is well formatted
  - lein cljfmt check
  # start a browser process for running kaocha tests
  - google-chrome-stable --no-first-run &
  # setup node dependencies
  - npm install

script:
  # Run unit tests
  - lein kaocha
  # ensure a minified build completes without error
  - lein uberjar
