language: java
jdk: openjdk8

before_script:
  # Install lein - required to build the project
  - wget https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein -O /tmp/lein
  - chmod +x /tmp/lein
  - export PATH=$PATH:/tmp/lein
  # make several attempts at downloading dependencies
  - travis_retry lein deps
  # check code is well formatted
  - lein cljfmt check
  # setup node dependencies
  - npm install

script:
  - Xvfb :99 -screen 0 1280x1024x24 &
  # Run unit tests
  - lein kaocha
  # ensure a minified build completes without error
  - lein uberjar
